[alembic]
script_location = alembic
sqlalchemy.url = postgresql+asyncpg://fake:fake@127.0.0.1:5432/fake_db

# log_template_format = %(levelname)-5.5s %(name)s %(message)s
# log_file = alembic.log
# log_level = info