"""add is_super field to merchant_admin

Revision ID: 417c7646a3a9
Revises: b59accd94bd1
Create Date: 2026-08-27 16:11:06.072481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417c7646a3a9'
down_revision: Union[str, Sequence[str], None] = 'b59accd94bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1.先新增字段，允许null
    op.add_column('merchant_admin', sa.Column('is_super', sa.Boolean(), nullable=True))
    # 2.存量全部赋值默认false
    op.execute("UPDATE merchant_admin SET is_super = false;")
    # 3.再改为非空约束
    op.alter_column('merchant_admin', 'is_super', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant_admin', 'is_super')
    # ### end Alembic commands ###
