"""init merchant and merchant_admin table

Revision ID: 48e45196b4e0
Revises: 
Create Date: 2026-08-13 16:23:38.763362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e45196b4e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='商家ID'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='商家唯一编码(URL路由使用)'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='商家名称'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_code'), 'merchant', ['code'], unique=True)
    op.create_table('merchant_admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False, comment='关联商家ID'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录账号'),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='密码哈希，不存储明文'),
    sa.Column('nickname', sa.String(length=64), nullable=True, comment='管理员昵称'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='账号启用状态'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_admin_merchant_id'), 'merchant_admin', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_merchant_admin_username'), 'merchant_admin', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_admin_username'), table_name='merchant_admin')
    op.drop_index(op.f('ix_merchant_admin_merchant_id'), table_name='merchant_admin')
    op.drop_table('merchant_admin')
    op.drop_index(op.f('ix_merchant_code'), table_name='merchant')
    op.drop_table('merchant')
    # ### end Alembic commands ###
