"""change merchant.status bool to string

Revision ID: b59accd94bd1
Revises: 48e45196b4e0
Create Date: 2026-08-27 16:07:42.499470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59accd94bd1'
down_revision: Union[str, Sequence[str], None] = '48e45196b4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=False)
    op.alter_column('merchant_admin', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               comment=None,
               existing_comment='账号启用状态',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_admin', 'status',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               comment='账号启用状态',
               existing_nullable=False)
    op.alter_column('merchant', 'status',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=False)
    # ### end Alembic commands ###
